
export const cardsData = [
    {
        _id: 1,
        projectImage: '/src/assets/card1.png',
        avatar: '/src/assets/Bianca.png',
        name: 'Bianca',
        lastName: 'Martin',
        createdAt: '02/24',
        title: 'Ecommerce One Page',
        tags: ['UX', 'Web'],
        description: 'Temos o prazer de compartilhar com vocês uma variação do nosso primeiro recurso gratuito. É um modelo de IA. Tentamos redesenhar uma versão mais minimalista do nosso primeiro projeto.',
        user: 1, 
        urlGithub: 'https://gumroad.com/products/wxCSL'
    },
    {
        _id: 2,
        projectImage: '/src/assets/card2.png',
        avatar: '/src/assets/Enzo.png',
        name: 'Enzo',
        lastName: 'Gabriel',
        createdAt: '12/23',
        title: 'Ecommerce ',
        tags: ['UX', 'Web'],
        description: '',
        user: 2, 
        urlGithub: 'https://gumroad.com/products/wxCSL'
    },
    {
        _id: 3,
        projectImage: '/src/assets/card3.png',
        avatar: '/src/assets/Alice.png',
        name: 'Alice',
        lastName: 'Alexandra',
        createdAt: '12/23',
        title: 'Landing Page',
        tags: ['UX', 'Web'],
        description: '',
        user: 3, 
        urlGithub: 'https://gumroad.com/products/wxCSL'
    },
    {
        _id: 4,
        projectImage: '/src/assets/card4.png',
        avatar: '/src/assets/Carolina.png',
        name: 'Carolina',
        lastName: 'Valentim',
        createdAt: '12/23',
        title: 'Chat bot',
        tags: ['UX', 'Web'],
        description: '',
        user: 4, 
        urlGithub: 'https://gumroad.com/products/wxCSL',
    },
];